export const labels = {
  aboutUs: {
    eng: 'Host a refugee is a website dedicated to helping the refugees fleeing ukraine.',
    ua: 'Host a refugee – це веб-сайт, присвячений допомозі біженцям, які тікають з України.',
    pl: 'Host a refugee to strona internetowa poświęcona pomocy uchodźcom uciekającym z Ukrainy.',
    sk: 'Host a refugee je webová stránka venovaná pomoci utečencom utekajúcim z Ukrajiny.',
    hu: 'Host a refugee egy olyan webhely, amely az Ukrajnából menekülő menekültek megsegítésére szolgál.',
    ro: 'Host a refugee este un site web dedicat ajutorării refugiaților care fug din Ucraina.',
    de: 'Host a Refugee ist eine Website, die sich der Hilfe für Flüchtlinge widmet, die aus der Ukraine fliehen.',
  },
  refugeeTitle: {
    eng: 'If you are a refugee:',
    ua: 'Created by ua',
    pl: 'Created by pl',
    sk: 'Created by sk',
    hu: 'Created by hu',
    ro: 'Created by ro',
    de: 'Created by de',
  },
  refugeeContent: {
    eng: ' Browse through the available hosts. Please be mindful of the capacity of your host concerning the amount of people, and the available dates. You can then contact a potential host directly',
    ua: 'Created by ua',
    pl: 'Created by pl',
    sk: 'Created by sk',
    hu: 'Created by hu',
    ro: 'Created by ro',
    de: 'Created by de',
  },
  hostTilte: {
    eng: 'If you can host:',
    ua: 'Created by ua',
    pl: 'Created by pl',
    sk: 'Created by sk',
    hu: 'Created by hu',
    ro: 'Created by ro',
    de: 'Created by de',
  },
  hostContent: {
    eng: 'Please register and become a host. We will ask you where, for how long, and how many people you can host. Refugees will then be able to contact you directly to arrange a hosting',
    ua: 'Created by ua',
    pl: 'Created by pl',
    sk: 'Created by sk',
    hu: 'Created by hu',
    ro: 'Created by ro',
    de: 'Created by de',
  },
};
