export const labels = {
  headerLocation: {
    eng: 'Location',
    ua: 'Location',
    pl: 'Location',
    sk: 'Location',
    hu: 'Location',
    ro: 'Location',
    de: 'Location',
  },
  headerDates: {
    eng: 'Dates',
    ua: 'Dates',
    pl: 'Dates',
    sk: 'Dates',
    hu: 'Dates',
    ro: 'Dates',
    de: 'Dates',
  },
  headerPeople: {
    eng: 'People',
    ua: 'People',
    pl: 'People',
    sk: 'People',
    hu: 'People',
    ro: 'People',
    de: 'People',
  },
  headerAbout: {
    eng: 'About',
    ua: 'About',
    pl: 'About',
    sk: 'About',
    hu: 'About',
    ro: 'About',
    de: 'About',
  },
};
