export const labels = {
  modalMessageHost: {
    eng: "Your registration was successful , we can't thank you enough for your support in these tough times 💗  We're working on matching you with a refuege and will be in touch with you as soon as possible!",
    ua: 'Ваша реєстрація пройшла успішно, ми не можемо подякувати вам за підтримку в ці важкі часи 💗 Ми працюємо над тим, щоб знайти вам притулок і зв’яжемося з вами якомога швидше!',
    pl: 'Twoja rejestracja się powiodła, nie możemy Ci podziękować za wsparcie w tych trudnych czasach 💗 Pracujemy nad dopasowaniem Cię do uchodźcy i skontaktujemy się z Tobą tak szybko, jak to możliwe!',
    sk: 'Vaša registrácia bola úspešná, nemôžeme vám dostatočne poďakovať za vašu podporu v týchto ťažkých časoch 💗 Pracujeme na tom, aby sme vás spojili s utečencom a budeme vás čo najskôr kontaktovať!',
    hu: 'Regisztrációd sikeres volt, nem tudjuk eléggé megköszönni a támogatásodat ezekben a nehéz időkben 💗 Dolgozunk azon, hogy találkozzunk egy menekülttel, és a lehető leghamarabb felvesszük veled a kapcsolatot!',
    ro: 'Înregistrarea dvs. a avut succes, nu vă putem mulțumi suficient pentru sprijinul acordat în aceste vremuri grele 💗 Lucrăm să vă potrivim cu un refugiat și vă vom contacta cât mai curând posibil!',
    de: 'Ihre Registrierung war erfolgreich, wir können Ihnen nicht genug für Ihre Unterstützung in diesen schwierigen Zeiten danken 💗 Wir arbeiten daran, Sie mit einem Flüchtling zusammenzubringen, und werden uns so schnell wie möglich mit Ihnen in Verbindung setzen!',
  },
  modalMessageRefugee: {
    eng: "Your registration was successful 💗  We're working on matching you with a host and will be in touch with you as soon as possible!",
    ua: 'Ваша реєстрація пройшла успішно 💗 Ми працюємо над тим, щоб знайти вас із хостом і зв’яжемося з вами якомога швидше!',
    pl: 'Twoja rejestracja powiodła się 💗 Pracujemy nad dopasowaniem Cię do hosta i skontaktujemy się z Tobą tak szybko, jak to możliwe!',
    sk: 'Vaša registrácia bola úspešná 💗 Pracujeme na tom, aby sme vás priradili k hostiteľovi a čo najskôr sa vám ozveme!',
    hu: 'Sikeres volt a regisztrációd 💗 Dolgozunk azon, hogy egy házigazdával találkozzunk, és a lehető leghamarabb felvesszük veled a kapcsolatot!',
    ro: 'Înregistrarea dvs. a avut succes 💗 Lucrăm să vă potrivim cu o gazdă și vă vom contacta cât mai curând posibil!',
    de: 'Ihre Registrierung war erfolgreich 💗 Wir arbeiten daran, Sie mit einem Gastgeber zusammenzubringen, und werden uns so schnell wie möglich mit Ihnen in Verbindung setzen!',
  },
  modalTitle: {
    eng: 'Success!',
    ua: 'Success!',
    pl: 'Success!',
    sk: 'Success!',
    hu: 'Success!',
    ro: 'Success!',
    de: 'Success!',
  },
  registerTypeLabel: {
    eng: 'Register type',
    ua: 'Register type',
    pl: 'Register type',
    sk: 'Register type',
    hu: 'Register type',
    ro: 'Register type',
    de: 'Register type',
  },
  registerTypePlaceholder: {
    eng: 'Refugee / Host',
    ua: 'Refugee / Host',
    pl: 'Refugee / Host',
    sk: 'Refugee / Host',
    hu: 'Refugee / Host',
    ro: 'Refugee / Host',
    de: 'Refugee / Host',
  },
  registerTypeError: {
    eng: 'Please select your registration type',
    ua: 'Please select your registration type',
    pl: 'Please select your registration type',
    sk: 'Please select your registration type',
    hu: 'Please select your registration type',
    ro: 'Please select your registration type',
    de: 'Please select your registration type',
  },
  phoneNumberLabel: {
    eng: 'Phone Number',
    ua: 'Phone Number',
    pl: 'Phone Number',
    sk: 'Phone Number',
    hu: 'Phone Number',
    ro: 'Phone Number',
    de: 'Phone Number',
  },
  phoneNumberPlaceholder: {
    eng: '+03 123 456 789',
    ua: '+03 123 456 789',
    pl: '+03 123 456 789',
    sk: '+03 123 456 789',
    hu: '+03 123 456 789',
    ro: '+03 123 456 789',
    de: '+03 123 456 789',
  },
  phoneNumberError: {
    eng: 'Please input a valid phone number and include the country code.',
    ua: 'Please input a valid phone number and include the country code.',
    pl: 'Please input a valid phone number and include the country code.',
    sk: 'Please input a valid phone number and include the country code.',
    hu: 'Please input a valid phone number and include the country code.',
    ro: 'Please input a valid phone number and include the country code.',
    de: 'Please input a valid phone number and include the country code.',
  },
  countryLabelRefugee: {
    eng: 'Destination country',
    ua: 'Destination country',
    pl: 'Destination country',
    sk: 'Destination country',
    hu: 'Destination country',
    ro: 'Destination country',
    de: 'Destination country',
  },
  countryLabelHost: {
    eng: 'Country of residence',
    ua: 'Country of residence',
    pl: 'Country of residence',
    sk: 'Country of residence',
    hu: 'Country of residence',
    ro: 'Country of residence',
    de: 'Country of residence',
  },
  countryPlaceholder: {
    eng: 'Country name ...',
    ua: 'Country name ...',
    pl: 'Country name ...',
    sk: 'Country name ...',
    hu: 'Country name ...',
    ro: 'Country name ...',
    de: 'Country name ...',
  },
  cityLabelHost: {
    eng: 'City of residence',
    ua: 'City of residence',
    pl: 'City of residence',
    sk: 'City of residence',
    hu: 'City of residence',
    ro: 'City of residence',
    de: 'City of residence',
  },
  cityLabelRefugee: {
    eng: 'Destination city',
    ua: 'Destination city',
    pl: 'Destination city',
    sk: 'Destination city',
    hu: 'Destination city',
    ro: 'Destination city',
    de: 'Destination city',
  },
  cityPlaceholder: {
    eng: 'City of ...',
    ua: 'City of ...',
    pl: 'City of ...',
    sk: 'City of ...',
    hu: 'City of ...',
    ro: 'City of ...',
    de: 'City of ...',
  },
  datesLabel: {
    eng: 'Accomodation dates',
    ua: 'Accomodation dates',
    pl: 'Accomodation dates',
    sk: 'Accomodation dates',
    hu: 'Accomodation dates',
    ro: 'Accomodation dates',
    de: 'Accomodation dates',
  },
  datesPlaceholder: {
    eng: 'Pick dates range',
    ua: 'Pick dates range',
    pl: 'Pick dates range',
    sk: 'Pick dates range',
    hu: 'Pick dates range',
    ro: 'Pick dates range',
    de: 'Pick dates range',
  },
  detailsLabel: {
    eng: 'Accomodation details',
    ua: 'Accomodation details',
    pl: 'Accomodation details',
    sk: 'Accomodation details',
    hu: 'Accomodation details',
    ro: 'Accomodation details',
    de: 'Accomodation details',
  },
  detailsPlaceholder: {
    eng: 'About the accomodation and Rules',
    ua: 'About the accomodation and Rules',
    pl: 'About the accomodation and Rules',
    sk: 'About the accomodation and Rules',
    hu: 'About the accomodation and Rules',
    ro: 'About the accomodation and Rules',
    de: 'About the accomodation and Rules',
  },
  groupSizeLabelHost: {
    eng: 'Number of people you can accomodate',
    ua: 'Number of people you can accomodate',
    pl: 'Number of people you can accomodate',
    sk: 'Number of people you can accomodate',
    hu: 'Number of people you can accomodate',
    ro: 'Number of people you can accomodate',
    de: 'Number of people you can accomodate',
  },
  groupSizeLabelRefugee: {
    eng: 'Number of people in your group',
    ua: 'Number of people in your group',
    pl: 'Number of people in your group',
    sk: 'Number of people in your group',
    hu: 'Number of people in your group',
    ro: 'Number of people in your group',
    de: 'Number of people in your group',
  },
  groupSizePlaceholder: {
    eng: 'Number of people',
    ua: 'Number of people',
    pl: 'Number of people',
    sk: 'Number of people',
    hu: 'Number of people',
    ro: 'Number of people',
    de: 'Number of people',
  },
  languagesLabel: {
    eng: 'Spoken languages',
    ua: 'Spoken languages',
    pl: 'Spoken languages',
    sk: 'Spoken languages',
    hu: 'Spoken languages',
    ro: 'Spoken languages',
    de: 'Spoken languages',
  },
  languagesPlaceholder: {
    eng: 'Pick the languages you can use',
    ua: 'Pick the languages you can use',
    pl: 'Pick the languages you can use',
    sk: 'Pick the languages you can use',
    hu: 'Pick the languages you can use',
    ro: 'Pick the languages you can use',
    de: 'Pick the languages you can use',
  },
  languagesError: {
    eng: 'Please select at least one language',
    ua: 'Please select at least one language',
    pl: 'Please select at least one language',
    sk: 'Please select at least one language',
    hu: 'Please select at least one language',
    ro: 'Please select at least one language',
    de: 'Please select at least one language',
  },
  tosLabel: {
    eng: 'I agree to the terms of service',
    ua: 'I agree to the terms of service',
    pl: 'I agree to the terms of service',
    sk: 'I agree to the terms of service',
    hu: 'I agree to the terms of service',
    ro: 'I agree to the terms of service',
    de: 'I agree to the terms of service',
  },
  buttonText: {
    eng: 'Submit',
    ua: 'Submit',
    pl: 'Submit',
    sk: 'Submit',
    hu: 'Submit',
    ro: 'Submit',
    de: 'Submit',
  },
};
